services:
    
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - internalnet

  postgres: 
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "DatabaseTest"
    volumes:
      - ./sql/01-create_table_order.sql:/docker-entrypoint-initdb.d/01-create_table_order.sql
    networks:
      - internalnet


networks:
  internalnet:
    driver: bridge